-- MySQL Script generated by MySQL Workbench
-- Mon Feb  8 12:49:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

use kinoreser;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movieone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movieone` (
  `movieoneid` INT NOT NULL,
  `rowoneseatone` VARCHAR(45) NULL,
  `rowoneseattwo` VARCHAR(45) NULL,
  `rowoneseatthree` VARCHAR(45) NULL,
  `rowoneseatfour` VARCHAR(45) NULL,
  `rowoneseatfive` VARCHAR(45) NULL,
  `rowoneseatsix` VARCHAR(45) NULL,
  `rowoneseatseven` VARCHAR(45) NULL,
  `rowoneseateight` VARCHAR(45) NULL,
  `rowoneseatnine` VARCHAR(45) NULL,
  `rowoneseatten` VARCHAR(45) NULL,
  `rowtwoseatone` VARCHAR(45) NULL,
  `rowtwoseattwo` VARCHAR(45) NULL,
  `rowtwoseatthree` VARCHAR(45) NULL,
  `rowtwoseatfour` VARCHAR(45) NULL,
  `rowtwoseatfive` VARCHAR(45) NULL,
  `rowtwoseatsix` VARCHAR(45) NULL,
  `rowtwoseatseven` VARCHAR(45) NULL,
  `rowtwoseateight` VARCHAR(45) NULL,
  `rowtwoseatnine` VARCHAR(45) NULL,
  `rowtwoseatten` VARCHAR(45) NULL,
  `rowthreeseatone` VARCHAR(45) NULL,
  `rowthreeseattwo` VARCHAR(45) NULL,
  `rowthreeseatthree` VARCHAR(45) NULL,
  `rowthreeseatfour` VARCHAR(45) NULL,
  `rowthreeseatfive` VARCHAR(45) NULL,
  `rowthreeseatsix` VARCHAR(45) NULL,
  `rowthreeseatseven` VARCHAR(45) NULL,
  `rowthreeseateight` VARCHAR(45) NULL,
  `rowthreeseatnine` VARCHAR(45) NULL,
  `rowthreeseatten` VARCHAR(45) NULL,
  `rowfourseatone` VARCHAR(45) NULL,
  `rowfourseattwo` VARCHAR(45) NULL,
  `rowfourseatthree` VARCHAR(45) NULL,
  `rowfourseatfour` VARCHAR(45) NULL,
  `rowfourseatfive` VARCHAR(45) NULL,
  `rowfourseatsix` VARCHAR(45) NULL,
  `rowfourseatseven` VARCHAR(45) NULL,
  `rowfourseateight` VARCHAR(45) NULL,
  `rowfourseatnine` VARCHAR(45) NULL,
  `rowfourseatten` VARCHAR(45) NULL,
  `rowfiveseatone` VARCHAR(45) NULL,
  `rowfiveseattwo` VARCHAR(45) NULL,
  `rowfiveseatthree` VARCHAR(45) NULL,
  `rowfiveseatfour` VARCHAR(45) NULL,
  `rowfiveseatfive` VARCHAR(45) NULL,
  `rowfiveseatsix` VARCHAR(45) NULL,
  `rowfiveseatseven` VARCHAR(45) NULL,
  `rowfiveseateight` VARCHAR(45) NULL,
  `rowfiveseatnine` VARCHAR(45) NULL,
  `rowfiveseatten` VARCHAR(45) NULL,
  `rowsixseatone` VARCHAR(45) NULL,
  `rowsixseattwo` VARCHAR(45) NULL,
  `rowsixseatthree` VARCHAR(45) NULL,
  `rowsixseatfour` VARCHAR(45) NULL,
  `rowsixseatfive` VARCHAR(45) NULL,
  `rowsixseatsix` VARCHAR(45) NULL,
  `rowsixseatseven` VARCHAR(45) NULL,
  `rowsixseateight` VARCHAR(45) NULL,
  `rowsixseatnine` VARCHAR(45) NULL,
  `rowsixseatten` VARCHAR(45) NULL,
  `rowsevenseatone` VARCHAR(45) NULL,
  `rowsevenseattwo` VARCHAR(45) NULL,
  `rowsevenseatthree` VARCHAR(45) NULL,
  `rowsevenseatfour` VARCHAR(45) NULL,
  `rowsevenseatfive` VARCHAR(45) NULL,
  `rowsevenseatsix` VARCHAR(45) NULL,
  `rowsevenseatseven` VARCHAR(45) NULL,
  `rowsevenseateight` VARCHAR(45) NULL,
  `rowsevenseatnine` VARCHAR(45) NULL,
  `rowsevenseatten` VARCHAR(45) NULL,
  `roweightseatone` VARCHAR(45) NULL,
  `roweightseattwo` VARCHAR(45) NULL,
  `roweightseatthree` VARCHAR(45) NULL,
  `roweightseatfour` VARCHAR(45) NULL,
  `roweightseatfive` VARCHAR(45) NULL,
  `roweightseatsix` VARCHAR(45) NULL,
  `roweightseatseven` VARCHAR(45) NULL,
  `roweightseateight` VARCHAR(45) NULL,
  `roweightseatnine` VARCHAR(45) NULL,
  `roweightseatten` VARCHAR(45) NULL,
  `rownineseatone` VARCHAR(45) NULL,
  `rownineseattwo` VARCHAR(45) NULL,
  `rownineseatthree` VARCHAR(45) NULL,
  `rownineseatfour` VARCHAR(45) NULL,
  `rownineseatfive` VARCHAR(45) NULL,
  `rownineseatsix` VARCHAR(45) NULL,
  `rownineseatseven` VARCHAR(45) NULL,
  `rownineseateight` VARCHAR(45) NULL,
  `rownineseatnine` VARCHAR(45) NULL,
  `rownineseatten` VARCHAR(45) NULL,
  `rowtenseatone` VARCHAR(45) NULL,
  `rowtenseattwo` VARCHAR(45) NULL,
  `rowtenseatthree` VARCHAR(45) NULL,
  `rowtenseatfour` VARCHAR(45) NULL,
  `rowtenseatfive` VARCHAR(45) NULL,
  `rowtenseatsix` VARCHAR(45) NULL,
  `rowtenseatseven` VARCHAR(45) NULL,
  `rowtenseateight` VARCHAR(45) NULL,
  `rowtenseatnine` VARCHAR(45) NULL,
  `rowtenseatten` VARCHAR(45) NULL,
  PRIMARY KEY (`movieoneid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cinemaroomone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cinemaroomone` (
  `cinemaroomoneid` INT NOT NULL,
  `movieoneid` INT NOT NULL,
  PRIMARY KEY (`cinemaroomoneid`),
  INDEX `fk_cinemaroomone_movieone_idx` (`movieoneid` ASC),
  CONSTRAINT `fk_cinemaroomone_movieone`
    FOREIGN KEY (`movieoneid`)
    REFERENCES `mydb`.`movieone` (`movieoneid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movietwo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movietwo` (
  `movietwoid` INT NOT NULL,
  PRIMARY KEY (`movietwoid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cinemaroomtwo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cinemaroomtwo` (
  `cinemaroomtwoid` INT NOT NULL,
  `movietwoid` INT NOT NULL,
  PRIMARY KEY (`cinemaroomtwoid`),
  INDEX `fk_cinemaroomtwo_movietwo1_idx` (`movietwoid` ASC),
  CONSTRAINT `fk_cinemaroomtwo_movietwo1`
    FOREIGN KEY (`movietwoid`)
    REFERENCES `mydb`.`movietwo` (`movietwoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`moviethree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`moviethree` (
  `moviethreeid` INT NOT NULL,
  PRIMARY KEY (`moviethreeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cinemaroomthree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cinemaroomthree` (
  `cinemaroomthreeid` INT NOT NULL,
  `moviethreeid` INT NOT NULL,
  PRIMARY KEY (`cinemaroomthreeid`),
  INDEX `fk_cinemaroomthree_moviethree1_idx` (`moviethreeid` ASC),
  CONSTRAINT `fk_cinemaroomthree_moviethree1`
    FOREIGN KEY (`moviethreeid`)
    REFERENCES `mydb`.`moviethree` (`moviethreeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
