-- MySQL Script generated by MySQL Workbench
-- Mon Feb  8 12:49:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kinoreser
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kinoreser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kinoreser` DEFAULT CHARACTER SET utf8 ;
USE `kinoreser` ;


-- -----------------------------------------------------
-- Table `kinoreser`.`seat`
-- -----------------------------------------------------
CREATE TABLE `kinoreser`.`seat` (
`seatid` INT NOT NULL,
`1` VARCHAR(45) NULL,
  `2` VARCHAR(45) NULL,
  `3` VARCHAR(45) NULL,
  `4` VARCHAR(45) NULL,
  `5` VARCHAR(45) NULL,
  `6` VARCHAR(45) NULL,
  `7` VARCHAR(45) NULL,
  `8` VARCHAR(45) NULL,
  `9` VARCHAR(45) NULL,
  `10` VARCHAR(45) NULL,
  `11` VARCHAR(45) NULL,
  `12` VARCHAR(45) NULL,
  `13` VARCHAR(45) NULL,
  `14` VARCHAR(45) NULL,
  `15` VARCHAR(45) NULL,
  `16` VARCHAR(45) NULL,
  `17` VARCHAR(45) NULL,
  `18` VARCHAR(45) NULL,
  `19` VARCHAR(45) NULL,
  `20` VARCHAR(45) NULL,
  `21` VARCHAR(45) NULL,
  `22` VARCHAR(45) NULL,
  `23` VARCHAR(45) NULL,
  `24` VARCHAR(45) NULL,
  `25` VARCHAR(45) NULL,
  `26` VARCHAR(45) NULL,
  `27` VARCHAR(45) NULL,
  `28` VARCHAR(45) NULL,
  `29` VARCHAR(45) NULL,
  `30` VARCHAR(45) NULL,
  `31` VARCHAR(45) NULL,
  `32` VARCHAR(45) NULL,
  `33` VARCHAR(45) NULL,
  `34` VARCHAR(45) NULL,
  `35` VARCHAR(45) NULL,
  `36` VARCHAR(45) NULL,
  `37` VARCHAR(45) NULL,
  `38` VARCHAR(45) NULL,
  `39` VARCHAR(45) NULL,
  `40` VARCHAR(45) NULL,
  `41` VARCHAR(45) NULL,
  `42` VARCHAR(45) NULL,
  `43` VARCHAR(45) NULL,
  `44` VARCHAR(45) NULL,
  `45` VARCHAR(45) NULL,
  `46` VARCHAR(45) NULL,
  `47` VARCHAR(45) NULL,
  `48` VARCHAR(45) NULL,
  `49` VARCHAR(45) NULL,
  `50` VARCHAR(45) NULL,
  `51` VARCHAR(45) NULL,
  `52` VARCHAR(45) NULL,
  `53` VARCHAR(45) NULL,
  `54` VARCHAR(45) NULL,
  `55` VARCHAR(45) NULL,
  `56` VARCHAR(45) NULL,
  `57` VARCHAR(45) NULL,
  `58` VARCHAR(45) NULL,
  `59` VARCHAR(45) NULL,
  `60` VARCHAR(45) NULL,
  `61` VARCHAR(45) NULL,
  `62` VARCHAR(45) NULL,
  `63` VARCHAR(45) NULL,
  `64` VARCHAR(45) NULL,
  `65` VARCHAR(45) NULL,
  `66` VARCHAR(45) NULL,
  `67` VARCHAR(45) NULL,
  `68` VARCHAR(45) NULL,
  `69` VARCHAR(45) NULL,
  `70` VARCHAR(45) NULL,
  `71` VARCHAR(45) NULL,
  `72` VARCHAR(45) NULL,
  `73` VARCHAR(45) NULL,
  `74` VARCHAR(45) NULL,
  `75` VARCHAR(45) NULL,
  `76` VARCHAR(45) NULL,
  `77` VARCHAR(45) NULL,
  `78` VARCHAR(45) NULL,
  `79` VARCHAR(45) NULL,
  `80` VARCHAR(45) NULL,
  PRIMARY KEY (`seatid`))
ENGINE = InnoDB;
  

-- -----------------------------------------------------
-- Table `kinoreser`.`users`
-- -----------------------------------------------------
CREATE TABLE `users` (
  `usersid` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kinoreser`.`movie`
-- -----------------------------------------------------
CREATE TABLE `kinoreser`.`movie` (
`movieid` INT NOT NULL,
`moviename` VARCHAR(255) NULL,
`duration` INT NOT NULL,
  PRIMARY KEY (`movieid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kinoreser`.`cinemaroomone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinoreser`.`cinemaroomone` (
  `cinemaroomoneid` INT NOT NULL,
  `movieid` INT NOT NULL,
  `usersid` INT NOT NULL,
  `seatid` INT NOT NULL,
  PRIMARY KEY (`cinemaroomoneid`),
  INDEX `fk_cinemaroomone_movie_idx` (`movieid` ASC),
  INDEX `fk_cinemaroomone_users_idx` (`usersid` ASC),
  INDEX `fk_cinemaroomone_seat_idx` (`seatid` ASC),
  CONSTRAINT `fk_cinemaroomone_movie`
    FOREIGN KEY (`movieid`)
    REFERENCES `kinoreser`.`movie` (`movieid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_cinemaroomone_users1`
    FOREIGN KEY (`usersid`)
    REFERENCES `kinoreser`.`users` (`usersid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_cinemaroomone_seat1`
    FOREIGN KEY (`seatid`)
    REFERENCES `kinoreser`.`seat` (`seatid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kinoreser`.`cinemaroomtwo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinoreser`.`cinemaroomtwo` (
  `cinemaroomtwoid` INT NOT NULL,
  `movieid` INT NOT NULL,
  `usersid` INT NOT NULL,
  `seatid` INT NOT NULL,
  PRIMARY KEY (`cinemaroomtwoid`),
  INDEX `fk_cinemaroomtwo_movie_idx` (`movieid` ASC),
  INDEX `fk_cinemaroomtwo_users_idx` (`usersid` ASC),
  INDEX `fk_cinemaroomone_seat_idx` (`seatid` ASC),
  CONSTRAINT `fk_cinemaroomtwo_movie`
    FOREIGN KEY (`movieid`)
    REFERENCES `kinoreser`.`movie` (`movieid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_cinemaroomtwo_users1`
    FOREIGN KEY (`usersid`)
    REFERENCES `kinoreser`.`users` (`usersid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_cinemaroomtwo_seat1`
    FOREIGN KEY (`seatid`)
    REFERENCES `kinoreser`.`seat` (`seatid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kinoreser`.`cinemaroomthree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinoreser`.`cinemaroomthree` (
  `cinemaroomthreeid` INT NOT NULL,
  `movieid` INT NOT NULL,
  `usersid` INT NOT NULL,
  `seatid` INT NOT NULL,
  PRIMARY KEY (`cinemaroomthreeid`),
  INDEX `fk_cinemaroomthree_movie1_idx` (`movieid` ASC),
  INDEX `fk_cinemaroomone_users_idx` (`usersid` ASC),
  INDEX `fk_cinemaroomone_seat_idx` (`seatid` ASC),
  CONSTRAINT `fk_cinemaroomthree_movie1`
    FOREIGN KEY (`movieid`)
    REFERENCES `kinoreser`.`movie` (`movieid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_cinemaroomthree_users1`
    FOREIGN KEY (`usersid`)
    REFERENCES `kinoreser`.`users` (`usersid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_cinemaroomthree_seat1`
    FOREIGN KEY (`seatid`)
    REFERENCES `kinoreser`.`seat` (`seatid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
